# file: roles/file_servers/tasks/main.yml
- name: install samba package
  tags: samba,smb
  package:
    name: samba
    state: latest

- name: Allow UDP/137
  ufw:
    rule: allow
    port: "137"
    proto: udp

- name: Allow UDP/138
  ufw:
    rule: allow
    port: "138"
    proto: udp

- name: Allow TCP/139
  ufw:
    rule: allow
    port: "139"
    proto: tcp

- name: Allow TCP/445
  ufw:
    rule: allow
    port: "445"
    proto: tcp
