# file: roles/file_servers/tasks/main.yml
- name: install samba package
  tags: samba,smb
  package:
    name: samba
    state: latest

- name: Add UFW rules for Debian
  when: ansible_os_family == 'Debian'
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: "137", proto: "udp" }
    - { port: "138", proto: "udp" }
    - { port: "139", proto: "tcp" }
    - { port: "445", proto: "tcp" }

- name: Restart UFW service
  when: ansible_os_family == 'Debian'
  service:
    name: ufw
    state: restarted

- name: FirewallD allow UDP/137-138 for CentOS
  when: ansible_os_family == 'RedHat' 
  ansible.posix.firewalld:
    zone: public
    port: 137-138/udp
    permanent: true
    state: enabled

- name: FirewallD allow TCP/139 for CentOS
  when: ansible_os_family == 'RedHat'
  ansible.posix.firewalld:
    zone: public
    port: 139/tcp
    permanent: true
    state: enabled

- name: FirewallD allow TCP/445 for CentOS
  when: ansible_os_family == 'RedHat'
  ansible.posix.firewalld:
    zone: public
    port: 445/tcp
    permanent: true
    state: enabled

- name: Restart Firewalld service
  when: ansible_os_family == 'RedHat'
  service:
    name: firewalld
    state: restarted
