- hosts: all
  become: true
  pre_tasks:
    - name: Update repository 
      tags: always
      changed_when: false   
      package:
        update_cache: yes

- hosts: all
  tags: always
  become: true
  roles:
    - basic

- hosts: unifi_controllers
  become: true
  roles:
    - unifi_controllers
 
- hosts: db_servers
  become: true
  roles:
    - db_servers
 
- hosts: file_servers
  become: true
  roles:
    - file_servers
