- hosts: all
  become: true
  pre_tasks:
    - name: Update package cache on Debian-based systems
      tags: always
      when: ansible_os_family == 'Debian'
      apt:
        update_cache: yes
        upgrade: dist

    - name: Update package cache on CentOS systems
      tags: always
      when: ansible_os_family == 'RedHat'
      yum:
        update_only: yes
        update_cache: yes


- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: create ansible user
      user:
       name: ansible-automate
       groups: root    

    - name: add ssh key for ansible-automate account
      tags: always
      authorized_key:
        user: ansible-automate
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILTcKkJ/QfC0TBmeUwGusFaitaDHHMcIQHa7wSHhoJDe ansible"

    - name: add sudoers file for ansible-automate
      tags: always
      copy:
        src: sudoer_ansible-automate
        dest: /etc/sudoers.d/ansible-automate
        owner: root
        group: root
        mode: 0440

- hosts: all
  become: true
  tags: ubuntu,debian,ufw
  tasks:    
    - name: Install Extra Packages for Enterprise Linux
      when: ansible_os_family == 'RedHat'
      yum:
        name: epel-release

    - name: Install ufw
      package:
        name: ufw
        state: present

    - name: Allow outgoing traffic in UFW
      shell: ufw default allow outgoing

    - name: Set default UFW rule to deny incoming
      shell: ufw default deny incoming

    - name: Allow SSH (port 22) with UFW
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Turn on UFW
      ufw:
        state: enabled

    - name: Start and enable UFW service
      service:
        name: ufw
        enabled: yes
        state: started

- hosts: all
  gather_facts: no
  become: true
  tags: nano
  tasks:
    - name: Install/Update nano
      package:
        name: nano
        state: latest

- hosts: all
  become: true
  gather_facts: no
  tags: rsyslog
  tasks:
    - name: Install rsyslog on Debian/Ubuntu
      package:
        name: rsyslog
        state: latest

   
    - name: Set timezone
      timezone:
        name: CET    

- hosts: all
  become: true
  tags: fail2ban
  tasks:
    - name: Install Fail2ban 
      package:
        name: fail2ban
        state: present

    - name: Run and enable Fail2ban
      service:
        name: fail2ban
        state: started
        enabled: yes
