- hosts: all
  become: true
  pre_tasks:
    - name: Update repository on Debian-based systems
      tags: always
      changed_when: false   
      when: ansible_os_family == 'Debian'
      apt:
        update_cache: yes

    - name: Update repository on CentOS systems
      tags: always
      changed_when: false
      when: ansible_os_family == 'RedHat'
      yum:
        update_cache: yes

- hosts: all
  tags: always
  become: true
  roles:
    - basic

- hosts: unifi_controllers
  become: true
  roles:
    - unifi_controllers
 
- hosts: db_servers
  become: true
  roles:
    - db_servers
 
- hosts: file_servers
  become: true
  roles:
    - file_servers
