- name: add ssh key for ansible-automate account
  authorized_key:
    user: ansible-automate
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILTcKkJ/QfC0TBmeUwGusFaitaDHHMcIQHa7wSHhoJDe ansible"

- name: Apply ssh template
  tags: ssh
  template:
    src: "{{ ssh_template }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: Apply firewall template
  tags: ufw
  template:
    src: "{{ ufw_src }}"
    dest: "{{ ufw_dst }}"
    owner: root
    group: root
    mode: 0644
  notify: restart_ufw

- name: Configure rsyslog for SSH connections
  tags: logs
  template:
    src: "sshconf.j2"
    dest: /etc/rsyslog.d/ssh.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_rsyslog

- name: Add local time to rsyslog dumps
  tags: logs
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^$LocalTime'
    line: $LocalTime on
  notify: restart_rsyslog
