# file: roles/db_servers/tasks/main.yml
- name: install mariadb server 
  tags: db
  package:
    name: "{{ mariadb_package_name }}"
    state: latest

- name: Allow TCP/3306
  ufw:
    rule: allow
    port: "3306"
    proto: tcp
